### ISSUE TITLE
Visually distinguish bozz's position on the leaderboard

### ISSUE THREAD

**Issue by fonglh** [fonglh/bozzbojiome#11]
With https://github.com/fonglh/bozzbojiome/pull/10, there should be a visual separator between the chosen one's name and the rest of the leaderboard to make it clear that the sort order is modified.

**Comment by jchiam** [comment]
Then why even put the chosen one in the table?

![screenshot 2018-10-09 at 11 39 53](https://user-images.githubusercontent.com/2408054/46645577-1023c200-cbb8-11e8-9e7c-0ee59198e815.png)
